/* La banque de chambrage.

   À chaque fois que quelqu'un se pèse, les autres se voient proposer deux
   phrases toutes faites : une pour encourager, une pour charrier. C'est ce
   qui transforme un tableau de chiffres en conversation — personne n'ouvre
   une application pour regarder une colonne de pourcentages, mais tout le
   monde revient voir ce que les copains ont répondu.

   `{n}` est remplacé par le pseudo de celui qui vient de se peser.

   Le registre est celui d'un vestiaire : familier, parfois grossier, jamais
   méchant sur ce qu'on ne choisit pas. On se moque de l'effort, du frigo et
   du classement — pas des gens. */

export const POSITIVES = [
  'Vas-y {n}, écrase tout.',
  '{n} est lancé, poussez-vous.',
  'Ça c’est du travail. Bravo {n}.',
  'Machine. Rien d’autre à dire.',
  '{n} a décidé que ce serait son mois.',
  'Chapeau, sincèrement.',
  'Tu tiens le rythme, continue comme ça.',
  'Voilà ce que ça donne quand on s’y met.',
  'Respect {n}, ça paye.',
  'On voit la différence, franchement.',
  'Le sérieux finit toujours par se voir.',
  'Beau boulot. Lâche rien.',
  '{n} ne joue pas, {n} travaille.',
  'Ça descend, et ça descend droit.',
  'Voilà, c’est exactement ça.',
  'Tu m’as mis une claque, bien joué.',
  'Impressionnant, très honnêtement.',
  '{n} est en train de nous mettre tout le monde d’accord.',
  'Continue, tu es sur la bonne pente.',
  'Solide. Vraiment solide.',
  'Ça, c’est un vrai chiffre.',
  'Tu as gagné ta soirée.',
  'La régularité, y a que ça.',
  'Bien vu {n}, c’est propre.',
  'Quelqu’un ici a compris le principe.',
  'Ça sent la forme.',
  'Tu mérites ta place là-haut.',
  'Franchement, bien joué.',
  'On y croit pour toi.',
  'Force à toi {n}, tu tiens le bon bout.',
  'Ça se voit que tu bosses.',
  'Le corps suit la tête, et là ça suit.',
  'Tu es en train de te faire plaisir, ça se sent.',
  'Bravo, pour de vrai.',
  'C’est ça l’état d’esprit.',
  'Beau chiffre, beau mois.',
  'Tu ne lâches rien, respect.',
  'Voilà comment on fait.',
  'Ça avance et c’est le principal.',
  'Petit à petit, mais ça avance.',
  'Même un petit pas est un pas.',
  'Rien n’est perdu, tu es dedans.',
  'Tu remontes, ça fait plaisir à voir.',
  'Allez {n}, on est derrière toi.',
  'Le classement va bouger, je le sens.',
  'Tu commences à faire peur.',
  'Ça pique de te voir monter.',
  'Je n’aime pas ça, mais bravo.',
  'Sale performance. Au bon sens.',
  '{n} sort les crocs.',
  'Là tu me fais douter.',
  'Bien joué, tu mérites.',
  'Ça y est, la machine est lancée.',
  'Tu tiens ta série, c’est le plus dur.',
  'Discipline. C’est le mot.',
  'Rien de spectaculaire, juste du sérieux.',
  'Le genre de progression qui dure.',
  'Tu fais ça bien, tranquillement.',
  'Pas de bruit, juste des résultats.',
  'C’est le travail de fond qui parle.',
  'Beau rythme, ne change rien.',
  'On dirait que ça devient une habitude.',
  'Ça, c’est du régulier.',
  'Tu es en train de gagner sans crier.',
  'Belle mécanique.',
  'Tu as trouvé ton truc, garde-le.',
  'La forme revient, ça se voit.',
  'Le padel va te sembler léger.',
  'Tu vas courir plus vite que nous tous.',
  'Tes genoux te disent merci.',
  'Ton cardio te remercie.',
  'Bientôt tu montes les escaliers sans souffler.',
  'Les vêtements commencent à flotter, non ?',
  'On va devoir refaire ta garde-robe.',
  'Ça se voit sur la tête en premier, et ça se voit.',
  'Ta montre doit être contente.',
  'La balance ne ment pas, bien joué.',
  'Tu as gagné ton droit de te la raconter.',
  'Vas-y, savoure, tu l’as mérité.',
  'Là tu peux te la péter un peu.',
  'Fier de toi, sincèrement.',
  'Tu envoies du lourd, enfin, de moins en moins.',
  'Beau bilan.',
  'Tu es au-dessus, assume.',
  'Personne ne va te rattraper comme ça.',
  'Continue et c’est plié.',
  'Ça devient sérieux.',
  'Tu es en train de plier le défi.',
  'On applaudit.',
  'Grosse semaine, bravo.',
  'Tu as tenu, c’est ça qui compte.',
  'Même les jours sans, tu tiens.',
  'Tu n’as rien lâché.',
  'La constance, ça se respecte.',
  'Rien à redire.',
  'Belle gestion.',
  'C’est propre et c’est net.',
  'Le genre de chiffre qui fait plaisir.',
  'Tu progresses bien.',
  'Une belle courbe.',
  'Ça descend joliment.',
  'Bravo pour la rigueur.',
  'Ton sérieux paye, ça fait plaisir.',
  'Continue exactement comme ça.',
  'Tu prends le bon chemin.',
  'Ça part très bien.',
  'Excellent démarrage.',
  'Le début est le plus dur, tu l’as passé.',
  'Tu as pris le rythme.',
  'Bien démarré, maintenant tiens.',
  'Un bon début, on attend la suite.',
  'Voilà une entrée en matière.',
  'Ça promet.',
  'Si tu tiens ça, tu gagnes.',
  'Tu es dans les temps.',
  'Tu es même en avance.',
  'Objectif en vue.',
  'Plus que quelques kilos et c’est bon.',
  'Tu y es presque.',
  'Ne lâche pas maintenant.',
  'Le plus dur est fait.',
  'Encore un effort et c’est dans la poche.',
  'Garde ce cap.',
  'Tu tiens le bon rythme, ne change rien.',
  'Tout est en place.',
  'Tu as les cartes en main.',
  'Beau combat.',
  'Tu te bats bien.',
  'Tu ne te laisses pas faire.',
  'Ça se joue à rien, accroche-toi.',
  'Encore un coup de reins.',
  'Tu peux les avoir.',
  'Rien n’est joué, vas-y.',
  'Tu as de la marge, utilise-la.',
  'Le podium est jouable.',
  'Tu peux encore remonter.',
  'La fin de défi va être belle.',
  'Ne baisse pas les bras si près du but.',
  'On y est presque.',
  'Dernière ligne droite.',
  'Tiens bon, ça se termine.',
  'Encore un peu de patience.',
  'Ça sera bientôt fini, tiens.',
  'Tu as fait le plus long.',
  'Beau parcours.',
  'Quel que soit le résultat, tu as bossé.',
  'Tu peux être content de toi.',
  'C’est déjà une victoire.',
  'Le chiffre est là, le reste suivra.',
  'Bien joué pour la constance.',
  'Ta courbe est belle à regarder.',
  'Je regarde ta courbe avec envie.',
  'Tu as la plus belle pente du groupe.',
  'Là tu me donnes envie de m’y mettre.',
  'Tu motives tout le monde.',
  'Grâce à toi je me suis pesé ce matin.',
  'Tu tires le groupe vers le haut.',
  'C’est toi le moteur de ce défi.',
  'Sans toi ce défi serait mou.',
  'Merci de mettre l’ambiance.',
  'Tu rends le truc intéressant.',
  'Avec toi c’est une vraie course.',
  'Ça me pousse à bosser, merci.',
  'Tu m’as remis un coup de pression, bien joué.',
  'Grâce à toi je vais devoir m’y mettre.',
  'Tu viens de me gâcher ma soirée pizza, bravo.',
  'À cause de toi je vais à la salle demain.',
  'Bien joué, tu viens de me motiver.',
  'Tu me forces à me bouger, merci.',
  'Ok, message reçu, je m’y mets.',
  'Tu me mets la pression et c’est tant mieux.',
  'Beau geste, sincèrement.',
  'On sent le mec sérieux.',
  'Tu es constant, c’est rare.',
  'Le genre de participant qu’on aime.',
  'Exemplaire.',
  'Rien à dire, du bon travail.',
  'Sérieux et régulier, la bonne recette.',
  'Ça se voit que tu t’accroches.',
  'Beaucoup abandonnent là, pas toi.',
  'Tu as passé le cap difficile.',
  'Le palier est cassé, bravo.',
  'Ça repart, excellent.',
  'Tu as débloqué la situation.',
  'Après une semaine dure, c’est encore mieux.',
  'Belle réaction.',
  'Tu as bien rebondi.',
  'Ça c’est du caractère.',
  'Tu ne t’es pas découragé, bravo.',
  'Tu reviens fort.',
  'Le retour est là.',
  'Ça repart dans le bon sens.',
  'Tu as corrigé le tir.',
  'Bonne remontée.',
  'Tu reprends du terrain.',
  'Ça se resserre grâce à toi.',
  'Le défi devient serré.',
  'Tu relances tout le monde.',
  'On ne s’ennuie pas avec toi.',
  'Beau sursaut.',
  'Excellent {n}, vraiment.',
  'Voilà du lourd.',
  'Bien vu.',
  'Nickel.',
  'Propre.',
  'Bien ouej.',
  'Costaud.',
  'Bravo champion.',
  'Grosse perf {n}.',
];

export const NEGATIVES = [
  'C’est tout ?',
  'Ah oui quand même. Dans l’autre sens.',
  '{n} a confondu défi et buffet.',
  'Tu t’es pesé avec les chaussures ?',
  'La balance a demandé grâce.',
  'On t’a connu plus rapide.',
  'À ce rythme tu finis en 2031.',
  'Doucement, tu vas te faire mal.',
  'Impressionnant. De lenteur.',
  'Tu es sûr d’avoir appuyé sur le bon bouton ?',
  'Il s’est passé quoi ce week-end ?',
  'Le kebab a gagné cette manche.',
  'La raclette t’a remis à ta place.',
  'Tu as mangé le défi ?',
  'Le frigo a eu ta peau.',
  'On dirait que quelqu’un a découvert la livraison à domicile.',
  'Tu confonds jeûne et jeune.',
  'Il reste combien de parts ?',
  'Le dimanche a été long, hein.',
  'L’apéro, ce traître.',
  'Ta courbe fait de la résistance.',
  'Ta courbe est plate comme mon moral.',
  'Ta courbe fait du sur-place, elle est zen.',
  'Belle ligne droite. Horizontale.',
  'Ta courbe et moi on a le même dynamisme.',
  'On voit que tu ne te presses pas.',
  'Tu gères ton effort. Trop bien.',
  'Tu es en mode économie d’énergie.',
  'Tu as mis le défi en pause ?',
  'Tu participes ou tu regardes ?',
  'On t’a perdu en route.',
  'Quelqu’un a vu {n} ?',
  'Avis de recherche : {n}, dernier signalement sur le canapé.',
  'Tu t’es endormi sur la balance ?',
  'Tu reviens quand ?',
  'On garde ta place au chaud, prends ton temps.',
  'La dernière place t’attend, elle est confortable.',
  'Elle est bien la vue d’en bas ?',
  'Tu tiens le bas du classement avec autorité.',
  'Solide dernier. Au moins tu es constant.',
  'Tu as trouvé ta place et tu t’y accroches.',
  'Personne ne te conteste cette place, rassure-toi.',
  'Le dernier a au moins le mérite d’être fidèle.',
  'Tu fermes la marche avec élégance.',
  'Quelqu’un doit bien être dernier.',
  'Merci de faire du bien à nos statistiques.',
  'Grâce à toi je me sens mieux.',
  'Tu remontes le moral du groupe.',
  'Continue, tu nous rassures.',
  'Sans toi je serais dernier, merci.',
  'Je compte sur toi pour ne pas progresser.',
  'Ne change rien surtout.',
  'Reste comme tu es, ça m’arrange.',
  'Tu es mon assurance podium.',
  'Mon plan de secours c’est toi.',
  'Tu es le gage sur pattes.',
  'Prépare la carte bleue pour la tournée.',
  'Commence à économiser pour le gage.',
  'Tu paies la prochaine, c’est déjà écrit.',
  'Le gage a ton nom dessus.',
  'On sait déjà qui paie.',
  'Réserve la table, tu régales.',
  'Tu veux qu’on t’aide à choisir le resto que tu paieras ?',
  'Pense à prendre ta carte demain.',
  'Le perdant est déjà connu, à ce stade.',
  'Suspense insoutenable pour la dernière place.',
  'Zéro virgule zéro. Poétique.',
  'Le néant, mais avec des décimales.',
  'Techniquement, c’est un chiffre.',
  'Mathématiquement ça existe.',
  'À la virgule près, tu n’as rien fait.',
  'Belle performance, au microscope.',
  'On va avoir besoin d’une loupe.',
  'Il faudrait une balance plus précise pour voir ça.',
  'Ta perte tient dans un dé à coudre.',
  'C’est l’épaisseur du trait.',
  'C’est de l’erreur de mesure, pas un résultat.',
  'Tu as transpiré, c’est déjà ça.',
  'Tu as bu un verre d’eau en moins, bravo.',
  'Coupe-toi les ongles, ça ira plus vite.',
  'Rase-toi la barbe, tu gagnes un rang.',
  'Vide tes poches avant de monter, on ne sait jamais.',
  'Enlève le pull, ça peut aider.',
  'Essaie de te peser après être passé aux toilettes.',
  'Pèse-toi le matin, pas après le dîner.',
  'Astuce : la balance ne compte pas les intentions.',
  'Les bonnes intentions, ça ne pèse rien malheureusement.',
  'Penser à faire du sport, ça ne compte pas.',
  'Regarder du sport non plus.',
  'Parler de sport encore moins.',
  'Tu as fait du sport ou tu as regardé le match ?',
  'La télécommande n’est pas un haltère.',
  'Le canapé n’est pas un banc de musculation.',
  'Ouvrir le frigo n’est pas un exercice.',
  'Monter chercher la pizza, ça compte pas.',
  'Le curl de fourchette, c’est pas du renfo.',
  'Le cardio du serveur de livraison, c’est pas le tien.',
  'Tu t’entraînes ou tu t’entretiens ?',
  'C’est un défi, pas un abonnement.',
  'S’inscrire et se peser, ce sont deux choses.',
  'L’inscription ne suffit pas, il faut jouer.',
  'Tu as payé pour regarder ?',
  'Spectateur de luxe.',
  'Beau maillot, dommage pour le jeu.',
  'Tu es là pour l’ambiance, on a compris.',
  'Merci pour l’animation.',
  'Tu apportes surtout la bonne humeur.',
  'Au moins tu es sympa.',
  'On t’aime bien quand même.',
  'Ce n’est pas grave, tu as d’autres qualités.',
  'Tu es meilleur au padel. Enfin j’espère.',
  'Reste au padel, c’est mieux pour tout le monde.',
  'Tu devrais essayer un autre sport. Ou un autre défi.',
  'Il paraît que les échecs c’est bien.',
  'La pétanque te tend les bras.',
  'Le curling recrute.',
  'Essaie le sumo, tu as le physique.',
  'Ne change rien, tu es parfait pour le rôle du lièvre. Ah non, la tortue.',
  'Tu joues la tortue, sauf qu’elle gagnait à la fin.',
  'La tortue, elle, avançait.',
  'Même un escargot motivé ferait mieux.',
  'Un continent dérive plus vite.',
  'Les plaques tectoniques te regardent avec mépris.',
  'La glace des pôles fond plus vite que toi.',
  'Un iceberg te met la honte.',
  'Une stalactite pousse plus vite que tu ne maigris.',
  'Tu perds du poids à la vitesse du carbone 14.',
  'Une éclipse arrive plus souvent que tes pesées.',
  'On se pèse plus souvent qu’on ne te voit ici.',
  'Une pesée par semaine, ça fait léger.',
  'Deux pesées en un mois, le grand luxe.',
  'Tu te pèses aux grandes occasions.',
  'La balance a pris la poussière.',
  'Elle est où ta balance, au grenier ?',
  'Tu l’as prêtée à quelqu’un, ta balance ?',
  'Elle marche encore ta balance ?',
  'Change les piles, ça ira mieux.',
  'Ta balance a dû rendre l’âme.',
  'La balance a fait une erreur, forcément.',
  'C’est la balance qui est cassée, évidemment.',
  'Toujours la faute de la balance.',
  'C’est les muscles, on sait.',
  'Le muscle pèse plus lourd, bien sûr.',
  'C’est de l’eau, évidemment.',
  'De la rétention d’eau, la meilleure excuse.',
  'Le stress, forcément.',
  'Les hormones, on connaît la chanson.',
  'C’est génétique, bien sûr.',
  'Tu as les os lourds, on sait.',
  'C’est la faute du métabolisme.',
  'Ton métabolisme a bon dos.',
  'Ça remonte, et pas qu’un peu.',
  'Ah, la remontada. Dans le mauvais sens.',
  'Tu montes. Au classement, non.',
  'Bravo, tu progresses. Vers le haut.',
  'Objectif inversé, c’est une stratégie ?',
  'Tu joues à l’envers ?',
  'Tu t’es trompé de défi.',
  'Le défi c’était de perdre, je précise.',
  'Petit rappel du règlement : on descend.',
  'On t’a expliqué le principe ?',
  'Tu veux qu’on te réexplique ?',
  'Quelqu’un peut lui traduire les règles ?',
  'Le but c’est moins, pas plus.',
  'Tu as inversé le signe.',
  'Moins, {n}. Moins.',
  'Tu as pris du poids et tu l’annonces, respect pour le courage.',
  'Au moins tu es honnête.',
  'L’honnêteté te perdra.',
  'Tu aurais pu mentir, personne n’aurait su.',
  'Courageux de publier ça.',
  'Il en faut du cran pour afficher ce chiffre.',
  'On admire la transparence, pas le chiffre.',
  'Merci de nous faire rire.',
  'Ça valait le coup d’ouvrir l’appli.',
  'Meilleure nouvelle de ma journée.',
  'Je souris pour la première fois aujourd’hui.',
  'Tu viens de me faire ma soirée.',
  'Capture d’écran envoyée au groupe.',
  'Ça va rester dans les annales.',
  'On en reparlera longtemps.',
  'Encadre-moi ce chiffre.',
  'Tu viens d’entrer dans la légende. La mauvaise.',
  'Un classique, déjà.',
  'Tu as battu un record. À l’envers.',
  'Personne n’avait fait pire, félicitations.',
  'Tu as trouvé le fond, tu creuses.',
  'Il y a un étage en dessous ?',
  'Le plancher n’était qu’une suggestion.',
  'Tu explores des territoires inconnus.',
  'Tu pousses les limites du possible.',
  'Scientifiquement intéressant.',
  'Les chercheurs vont vouloir t’étudier.',
  'Ça mérite une publication.',
  'Tu as tenu deux jours, c’est déjà ça.',
  'La motivation a duré, quoi, 48 heures ?',
  'Le feu sacré s’est éteint vite.',
  'Belle flamme, courte.',
  'Tu as commencé fort, dommage pour la suite.',
  'Le début était prometteur.',
  'On y a cru un moment.',
  'Tu nous avais fait espérer.',
  'Que s’est-il passé ?',
  'Raconte, on est curieux.',
  'Tu veux en parler ?',
  'Tout va bien chez toi ?',
  'On peut faire quelque chose pour t’aider ?',
  'Tu as besoin qu’on vienne te chercher ?',
  'Faut qu’on t’appelle ?',
  'Tu es encore en vie ?',
  'Un signe de vie serait apprécié.',
  'Tape un message si tu es retenu contre ton gré par un frigo.',
  'Cligne deux fois si le kebab te tient en otage.',
  'Allez, secoue-toi un peu.',
  'Bouge-toi les fesses.',
  'Réveille-toi {n}.',
  'On se ressaisit.',
  'Ça suffit maintenant.',
  'Tu vaux mieux que ça.',
  'Prouve-nous le contraire.',
  'Fais-moi mentir.',
];

/* ---------------- Tirage ----------------
   Le même évènement doit proposer la même paire à tout le monde : sans ça,
   deux personnes se renvoient des phrases différentes et la conversation
   perd son sens. D'où un tirage déterministe à partir de l'identifiant. */

function graine(texte) {
  let h = 2166136261;
  for (let i = 0; i < texte.length; i++) {
    h ^= texte.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

export function rendre(phrase, nom) {
  return String(phrase).replace(/\{n\}/g, nom || 'quelqu’un');
}

/** Une phrase de chaque, pour un évènement donné. `tour` fait tourner l'offre. */
export function suggestions(evenementId, nom, tour = 0) {
  const g = graine(`${evenementId}:${tour}`);
  return {
    pour: rendre(POSITIVES[g % POSITIVES.length], nom),
    contre: rendre(NEGATIVES[Math.floor(g / POSITIVES.length) % NEGATIVES.length], nom),
  };
}

export const REACTIONS = ['🔥', '💪', '😂', '💀', '🐷', '👏'];
